module GlobalConstants
URLS = ["https://github.com/bad6e",
            "https://github.com/roseak",
            "https://github.com/mcschatz",
            "https://github.com/travishaby",
            "https://github.com/Jpease1020",
            "https://github.com/jphoenix86",
            "https://github.com/HoffsMH",
            "https://github.com/MowAlon",
            "https://github.com/russelleh",
            "https://github.com/jbrr",
            "https://github.com/rasensio1",
            "https://github.com/selfup",
            "https://github.com/dastinnette",
            "https://github.com/mbburch",
            "https://github.com/Kealii",
            "https://github.com/Unsafepond",
            "https://github.com/ChrisCenatie",
            "https://github.com/adamki",
            "https://github.com/plato721",
            "https://github.com/Egogre"]
end